# Common Application properties
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html

# -------------------------------------------------------------------------------------------------------------
# DATA PROPERTIES
# -------------------------------------------------------------------------------------------------------------

spring:

  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    # JDBC URL of the database.
    url: jdbc:mysql://localhost:3306/rabbitmq1?useSSL=false&allowPublicKeyRetrieval=true
    # Fully qualified name of the JDBC driver. Auto-detected based on the URL by default.
    driverClassName: com.mysql.cj.jdbc.Driver
    # Username of the database to execute DML scripts (if different).
    username: rabbitmq-user1
    # Password of the database to execute DML scripts (if different).
    password: Rabbitmq123#

  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    # Print the queries
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        # Pretty print the SQL
        format_sql: true
    hibernate:
      # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property.
      # Defaults to "create-drop" when using an embedded database and no schema manager was detected.
      # Otherwise, defaults to "none".
      ddl-auto: update
      # Fully qualified name of the physical naming strategy.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# -------------------------------------------------------------------------------------------------------------
# DATA MIGRATION PROPERTIES
# -------------------------------------------------------------------------------------------------------------

  flyway:
    # Whether to enable flyway.
    enabled: true
    # Locations of migrations scripts. Can contain the special "{vendor}" placeholder to use vendor-specific locations.
    locations: classpath:/data/mysql/migrations